config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :ants, only: %i[index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/ants_controller.rb
class AntsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/ants_helper.rb
module AntsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ants/index.html.erb
<main>
  <%= content_tag(:canvas, '', data: { controller: 'ants-threejs' }) %>
  <div class="text-group">
    <h1>アリンコ一人称</h1>
    <%= content_tag(:div, '', id: 'userName') %>
    <div id="button-group" class="button-group d-flex justify-content-around text-center mb-2">
      <div id="cross-key" class="d-flex flex-column">
        <div id="key-w" class="keybord mx-auto">W</div>
        <div class="key-ad d-flex justify-content-between mx-auto">
          <div id="key-a" class="keybord">A</div>
          <div id="key-d" class="keybord">D</div>
        </div>
        <div id="key-s" class="keybord mx-auto">S</div>
      </div>
      <div id="bullet-key">
        <div id="key-like" class="bullet-button">餌発射</div>
      </div>
    </div>
  </div>
</main>
<div id="explanation" class="text-center d-flex align-items-center justify-content-center"">
  <div id="pc">
    <div class="h3">WASDキーで移動<br>Spaceキーでいいねを発射</div>
    <div>クリックSTART!</div>
  </div>
  <div id="phone">
    <div class="h3">WASDで移動<br>餌ボタンでいいねを発射</div>
    <div>タップでSTART!</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThreejsAndRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= content_tag(:canvas, '', data: { controller: 'threejs' }) %>
<main>
  <h1><%= link_to "アリンコ", ants_path %></h1>
  <h1>初めてのthree.js</h1>
  <p>クリックしながらスクロール</p>
</main>